name: 'Neopo Build'
description: 'Build the project with neopo'
inputs:
  project-path:
    description: 'Path of project to build'
    required: true
    default: '.'
outputs:
  random-number: 
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps: 
    - run: git clone "https://github.com/nrobinson2000/neopo" && neopo/install.sh
      shell: bash
    - run: neopo build "${{ inputs.project-path }}"
      shell: bash