on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Build test project with Neopo
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.neopo
          ~/.particle
        key: ${{ runner.os }}-${{ hashFiles('**/manifest.json') }}
    - id: foo
      uses: nrobinson2000/neopo-action@v1.2
      with:
        project-path: 'test'
    - run: echo random-number ${{ steps.foo.outputs.random-number }} 
      shell: bash
