on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Build test project with Neopo
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.local/share/neopo
        key: ${{ runner.os }}-neopo-${{ hashFiles('**/settings.json') }}
    - uses: nrobinson2000/neopo-action@v1.2
      with:
        project-path: 'test'