on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
    - id: foo
      uses: nrobinson2000/neopo-action@v1.1
      with:
        who-to-greet: 'Nathan Robinson'
    - run: echo random-number ${{ steps.foo.outputs.random-number }} 
      shell: bash
